apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: squad-plataforma
  description: Squad Plataforma
spec:
  type: team
  profile:
    email: squad-plataforma@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: plataforma
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Daniel-dos-Santos-de-Godoi
  description: Squad Plataforma
  annotations:
    uoledtech.org/email: 'dagodoi+edtech@uoledtech.com'
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Daniel dos Santos de Godoi
    email: 'dagodoi+edtech@uoledtech.com'
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Fernando-Jensen-Junior
  description: Squad Plataforma
  annotations:
    uoledtech.org/email: fjensen@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Fernando Jensen Junior
    email: fjensen@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Fillipe-Almeida-Paz
  description: Squad Plataforma
  annotations:
    uoledtech.org/email: fpaz@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Fillipe Almeida Paz
    email: fpaz@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Lucas-Rodrigues-Miglioranca-Molfese-Da-Silva
  description: Squad Plataforma
  annotations:
    uoledtech.org/email: lmolfese@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Lucas Rodrigues Miglioranca Molfese Da Silva
    email: lmolfese@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Paulo-Henrique-Da-Silva-De-Melo
  description: Squad Plataforma
  annotations:
    uoledtech.org/email: pmelo@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Paulo Henrique Da Silva De Melo
    email: pmelo@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Romario-Alves-De-Oliveira-Campos
  description: Squad Plataforma
  annotations:
    uoledtech.org/email: rcampos1@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Romario Alves De Oliveira Campos
    email: rcampos1@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Vinicius-Granai
  description: Squad Plataforma
  annotations:
    uoledtech.org/email: vgranai@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Vinicius Granai
    email: vgranai@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Rafael-Bueno-De-Lara
  description: Tribo Core
  annotations:
    uoledtech.org/email: rblara@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Rafael Bueno De Lara
    email: rblara@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Rodrigo-Victor-Varanda
  description: Tribo Core
  annotations:
    uoledtech.org/email: rvaranda@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Rodrigo Victor Varanda
    email: rvaranda@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Gustavo-Mesquita-Da-Silveira
  description: Tribo Core
  annotations:
    uoledtech.org/email: gmsilveira@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Gustavo Mesquita Da Silveira
    email: gmsilveira@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Felipe-Henrique-Ferraresi
  description: Tribo Core
  annotations:
    uoledtech.org/email: fferraresi@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Felipe Henrique Ferraresi
    email: fferraresi@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Danilo-Narnatonis-De-Moraes-Oliveira
  description: Tribo Core
  annotations:
    uoledtech.org/email: dnarnatonis@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Danilo Narnatonis De Moraes Oliveira
    email: dnarnatonis@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Lucas-Pinto-Queiroz-Da-Rosa
  description: Tribo Core
  annotations:
    uoledtech.org/email: lqrosa@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Lucas Pinto Queiroz Da Rosa
    email: lqrosa@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Jaelson-Apolinario-de-Oliveira
  description: Tribo Core
  annotations:
    uoledtech.org/email: japolinario@uoledtech.com
  tags:
    - squad-plataforma
spec:
  profile:
    displayName: Jaelson Apolinario de Oliveira
    email: japolinario@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [squad-plataforma]
---
 apiVersion: backstage.io/v1alpha1
 kind: User
 metadata:
   name: Miguel-Braga-Garcia
   description: Tribo Core
   annotations:
     uoledtech.org/email: mgarcia2@uoledtech.com
   tags:
     - squad-plataforma
 spec:
   profile:
     displayName: Miguel Braga Garcia
     email: mgarcia2@uoledtech.com
     picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
   memberOf: [squad-plataforma]
