apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Create-Bucket-S3
  title: Criação Bucket S3
  description: Realize a criação de um Bucket S3
spec:
  owner: squad-plataforma
  type: infra-as-code
  parameters:

    - title: Grupo
      required:
        - grupo
      properties:
        grupo:
          title: Grupo
          type: string
          description: Selecione a Squad
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Ambiente
      required:
        - account_id
      properties:
        account_id:
          title: Selecione o Ambiente
          type: string
          description: selecione o ambiente que deseja realizar a criação do novo recurso
          enum:
            - "002382960105"
            - "333955165884"
            - "647703120685"
            - "057422990009"
            - "978185330044"
            - "853597464445"
            - "690033744245"
            - "592353520627"
            - "992382650049"
            - "948424637866"
            - "302878384879"
            - "192393990768"
            - "579579651374"
            - "020521381911"
          enumNames:
            - Instituição de Ensino - Desenvolvimento
            - Instituição de Ensino - Homologação
            - Hub - Desenvolvimento
            - Hub - Homologação
            - Hub - Produção
            - Instituição de Ensino - PUCRS
            - Instituição de Ensino - FAAP
            - Instituição de Ensino - UNINASSAU
            - Instituição de Ensino - Santa Casa
            - PUCRS - PÓS
            - PUCRS PÓS - Homologação
            - FIA
            - FIA - Homologação
            - UNESC

    - title: Tags de Ambiente
      required: [ ambiente, subarea ]
      properties:
        ambiente:
          title: Selecione a Tag Referente ao Ambiente
          type: string
          description: selecione a Tag Referente ao Ambiente
          enum: [ "develop", "homolog", "production"]
        subarea:
          title: Selecione a Tag Referente ao Ambiente
          type: string
          description: selecione a Tag Referente ao Ambiente
          enum: ["ie-dev", "ie-hmg", "hub-dev", "hub-hmg", "hub-prod", "ie-pucrs", "ie-faap", "ie-uninassau", "ie-santa-casa", "ie-unesc", "pucrs-pos-prod", "pucrs-pos-hmg", "fia-pos-prod", "fia-pos-hmg", "unesc-pos-prod", "unesc-pos-hmg"]
            
    - title: Key 
      required: [ resource_name, bucket_acl ]
      properties:
        resource_name:
          title: Bucket S3 Name
          type: string
          description: Insira o nome do Bucket S3
          minLength: 3
          maxLength: 63
          #pattern: ^(s3)-(.*)-(ie-dev|ie-hmg|hub-dev|hub-hmg|fia|fia-hmg|pucrs-pos|pucrs-pos-hmg|prod)$
          ui:help: 'mínimo de 3 e máximo de 63 caracteres.'
          ui:
            autofocus: true
            options:
            rows: 5

        bucket_acl:
          title: Bucket ACL
          type: string
          description: Insira o Bucket ACL
          ui:
            autofocus: true
            options:
            rows: 5

        cloudfront_id:
          title: Cloudfront ID
          type: string
          description: Em caso de comunicação com Cloudfront insira o ID (Opcional)
          ui:
            autofocus: true
            options:
            rows: 5

    # - title: Choose a location
    #   properties:
    #     repoUrl:
    #       title: GitAuth
    #       type: string
    #       default: github.com
    #       readOnly: true
    #       ui:options:
    #         requestUserCredentials:
    #           secretsKey: USER_OAUTH_TOKEN
    #         allowedHosts:
    #           - github.com

  steps:          
    - id: template
      if: ${{ parameters.account_id === "002382960105" }} #ie-dev
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/ie-dev/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : develop
          subarea            : ${{ parameters.subarea }}
      
    - id: template
      if: ${{ parameters.account_id === "333955165884" }} #ie-hmg
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/ie-hmg/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : homolog
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "647703120685" }} #hub-dev
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/hub-dev/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : develop
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "057422990009" }} #hub-hmg
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/hub-hmg/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : homolog
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "978185330044" }} #hub-prod
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/hub-prod/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : production
          subarea            : ${{ parameters.subarea }}
          
    - id: template
      if: ${{ parameters.account_id === "853597464445" }} #IE PUCRS
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/ie-pucrs/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : production
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "690033744245" }} #IE FAAP
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/ie-faap/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : production
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "592353520627" }} #IE UNINASSAU
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/ie-uninassau/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : "opm"
          ambiente           : "production"
          subarea            : ${{ parameters.subarea }}
  
    - id: template
      if: ${{ parameters.account_id === "992382650049" }} #IE SANTA CASA
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/ie-santa-casa/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : "opm"
          ambiente           : "production"
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "020521381911" }} #IE UNESC
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/ie-unesc/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : "opm"
          ambiente           : "production"
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "386886142089" }} #UNESC POS HMG
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/unesc-pos-hmg/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : "opm"
          ambiente           : "homolog"
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "948424637866" }} #PUC POS
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/pucrs-pos-prod/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : production
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "302878384879" }} #PUC POS HMG
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/pucrs-pos-hmg/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : homolog
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "192393990768" }} #FIA POS PROD
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/fia-pos-prod/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : production
          subarea            : ${{ parameters.subarea }}

    - id: template
      if: ${{ parameters.account_id === "579579651374" }} #FIA POS HMG
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/tf-aws-s3/tree/main/module/skeleton/
        values:
          resource_name      : ${{ parameters.resource_name }}
          bucket_acl         : ${{ parameters.bucket_acl }}
          account_id         : ${{ parameters.account_id }}
          key                : edtech-payer/opm/fia-pos-hmg/backstage/bucket-s3/${{ parameters.resource_name }}/terraform.tfstate
          area               : opm
          ambiente           : homolog
          subarea            : ${{ parameters.subarea }}

    - id: show_workspace
      name: Show workspace files
      action: debug:log
      input:
        listWorkspace: true
  
    - id: terraform_pr
      name: Create terraform PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=uoledtech-infra-as-code&repo=repositorio-versionamento
        branchName: 'feat/api-key'
        title: '🔩 Create AWS API Key'
        token : ${{ secrets.USER_OAUTH_TOKEN }}
        description: |
          ## ⚡ OPM - Platform Engineering ⚡

          ![N|Solid](https://hub-certificados-dev-assets.edtech.com.br/project-arrow/arrow_logo_v2.png)
          --- ---
          ### Dados da Solicitação

          |        |		   |
          | ------ | ----- |
          | Bucket S3    | ${{ parameters.resource_name }}
          | Bucket acl   | ${{ parameters.bucket_acl }}
          | Ambiente     | ${{ parameters.ambiente }}
          | Squad        | ${{ parameters.grupo }}
 

          --- ---
          ### 🚀 Para proseguir com provisionamento siga os passos abaixo:
          ### 1º - Execute o comando abaixo no campo de comentário, para planejar o recurso:
          ```
          atlantis plan -d tf-aws-${{ parameters.subarea }}/globals/tf-aws-s3/tf-${{ parameters.resource_name }}
          ```
          ### 2º - Execute o comando abaixo no campo de comentário, para provisionar o recurso:
          ```
          atlantis apply -d tf-aws-${{ parameters.subarea }}/globals/tf-aws-s3/tf-${{ parameters.resource_name }}
          ```

        sourcePath: ./
        #targetPath: baucket-s3/backstage/${{ parameters.ambiente }}/${{ parameters.subarea }}/tf-${{ parameters.resource_name }}
        targetPath: tf-aws-${{ parameters.subarea }}/globals/tf-aws-s3/tf-${{ parameters.resource_name }}


  output:
    links:
      - title: 'Go to pull request'
        url: ${{ steps.terraform_pr.output.remoteUrl }}
        icon: github
