apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template-teste-campos
  title: Template Teste Campos
  description: template-teste-campos
spec:
  owner: squad-plataforma
  type: infra-as-code
  parameters:
    - title: Grupo
      required:
        - grupo
      properties:
        grupo:
          title: Grupo
          type: string
          description: Selecione a Squad
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Ambiente
      required:
        - account_id
      properties:
        account_id:
          title: Selecione o Ambiente
          type: string
          description: selecione o ambiente que deseja realizar a criação do novo recurso
          enum:
            - "002382960105"
            - "333955165884"
            - "647703120685"
            - "057422990009"
            - "978185330044"
            - "853597464445"
            - "690033744245"
            - "592353520627"
            - "992382650049"
            - "948424637866"
            - "302878384879"
            - "192393990768"
            - "579579651374"
            - "020521381911"
          enumNames:
            - Instituição de Ensino - Desenvolvimento
            - Instituição de Ensino - Homologação
            - Hub - Desenvolvimento
            - Hub - Homologação
            - Hub - Produção
            - Instituição de Ensino - PUCRS
            - Instituição de Ensino - FAAP
            - Instituição de Ensino - UNINASSAU
            - Instituição de Ensino - Santa Casa
            - PUCRS - PÓS
            - PUCRS PÓS - Homologação
            - FIA
            - FIA - Homologação
            - UNESC

    - title: Tags de Ambiente
      required: [ ambiente, subarea ]
      properties:
        ambiente:
          title: Selecione a Tag Referente ao Ambiente
          type: string
          description: selecione a Tag Referente ao Ambiente
          enum: [ "develop", "homolog", "production"]
        subarea:
          title: Selecione a Tag Referente ao Ambiente
          type: string
          description: selecione a Tag Referente ao Ambiente
          enum: ["ie-dev", "ie-hmg", "hub-dev", "hub-hmg", "hub-prod", "ie-pucrs", "ie-faap", "ie-uninassau", "ie-santa-casa", "ie-unesc", "pucrs-pos-prod", "pucrs-pos-hmg", "fia-pos-prod", "fia-pos-hmg", "unesc-pos-prod", "unesc-pos-hmg"]

    - title: VPC
      required: [ resource_name, cidr_block, subnet_ranges, region ]
      properties:
        resource_name:
          title: VPC Name
          type: string
          description: Defina um nome para a VPC
          pattern: '^vpc-(.*)-(ie-dev|ie-hmg|hub-dev|hub-hmg|fia|fia-hmg|pucrs-pos|pucrs-pos-hmg|prod)$'
          ui:help: 'O nome da VPC deve começar com: "vpc-" e terminar com uma das opções a seguir: "ie-dev", "ie-hmg", "hub-dev", "hub-hmg", "prod", "fia", "fia-hmg", "pucrs-pos", "pucrs-pos-hmg"'
          ui:
            autofocus: true
            options:
              rows: 5
        cidr_block:
          title: cidr-block
          type: string
          description: Defina o cidr-block
          ui:
            autofocus: true
            options:
              rows: 5
        subnet_ranges:
          title: Subnet Ranges 
          type: string
          description: Defina o range da Subnet 
          ui:
            autofocus: true
            options:
              rows: 5
        region:
          title: Region 
          type: string
          default: "us-east-1"
          enum:
            - "us-east-1"


    # - title: Choose a location
    #   required:
    #     - repoUrl
    #   properties:
    #     repoUrl:
    #       title: Repository Location
    #       type: string
    #       ui:field: RepoUrlPicker
    #       ui:options:
    #         # Here's the option you can pass to the RepoUrlPicker
    #         requestUserCredentials:
    #           secretsKey: USER_OAUTH_TOKEN
    #           additionalScopes:
    #             github:
    #               - workflow
    #         allowedHosts:
    #           - github.com

    # - title: Choose a location
    #   properties:
    #     repoUrl:
    #       title: GitAuth
    #       type: string
    #       default: github.com
    #       readOnly: true
    #       ui:options:
    #         requestUserCredentials:
    #           secretsKey: USER_OAUTH_TOKEN
    #         allowedHosts:
    #           - github.com

  steps:          
    - id: template
      name: Render terraform files
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/uoledtech-infra-as-code/teste-backstage-pr/blob/main/skeleton/
        values:
          resource_name       : "${{ parameters.resource_name }}"
          account_id          : "${{ parameters.account_id }}"
          cidr_block          : "${{ parameters.cidr_block }}"
          subnet_ranges       : "${{ parameters.subnet_ranges }}"
          region              : "${{ parameters.region }}"
          area                : "opm"
          ambiente            : "develop"
          subarea             : ${{ parameters.subarea }} # "ie"
          availability_zones  : "us-east-1a, us-east-1b, us-east-1c"
          subnets             : ["subnet-07b1b51ba7a0fd5fb","subnet-0ebfeedad1707d2d9"]
          key                 : "edtech-payer/opm/ie-dev/backstage/vpc/${{ parameters.resource_name }}/terraform.tfstate"
          tag                 : "ie-dev"

  
    - id: show_workspace
      name: Show workspace files
      action: debug:log
      input:
        listWorkspace: true

    # - id: copy_lambda_function_zip
    #   name: Copy zip files
    #   action: fetch:plain
    #   input:
    #     url: https://github.com/uoledtech-infra-as-code/tf-aws-vpc/blob/main/module/skeleton/zip/
    #     targetPath: ./
    
    - id: terraform_pr
      name: Create terraform PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=uoledtech-infra-as-code&repo=teste-backstage-pr
        branchName: 'feat/${{ parameters.resource_name }}'
        title: '🔩 Create ${{ parameters.resource_name }} AWS VPC'
        token : ${{ secrets.USER_OAUTH_TOKEN }}
        description: |
          ## ⚡ OPM - Platform Engineering ⚡

          ![N|Solid](https://hub-certificados-dev-assets.edtech.com.br/project-arrow/arrow_logo_v2.png)
          --- ---
          ### Dados da Solicitação
          
          |        |		   |
          | ------ | ----- |
          | TESTE          | ${{ parameters.resource_name }} 
          | Squad        | ${{ parameters.grupo }}

          --- ---
          ### 🚀 Para proseguir com provisionamento siga os passos abaixo:
          ### 1º - Execute o comando abaixo no campo de comentário, para planejar o recurso:
          ```
          atlantis plan -d tf-aws-${{ parameters.subarea }}/network/vpc/tf-${{ parameters.resource_name }}
          ```
          ### 2º - Execute o comando abaixo no campo de comentário, para provisionar o recurso:
          ```
          atlantis apply -d tf-aws-${{ parameters.subarea }}/network/vpc/tf-${{ parameters.resource_name }}
          ```

        #description: '${{ parameters.grupo }} | user: ${{ secrets.USER_OAUTH_TOKEN }}'
        #commitMessage: 'atlantis plan -d lambda/lambda-vpc-and-sqs/${{ parameters.ambiente }}/${{ parameters.subarea }}/tf-${{ parameters.resource_name }}'
        sourcePath: ./
        targetPath: tf-aws-${{ parameters.subarea }}/network/vpc/tf-${{ parameters.resource_name }}
        #targetPath: vpc/backstage/${{ parameters.ambiente }}/${{ parameters.subarea }}/tf-${{ parameters.resource_name }}

  output:
    links:
      - title: 'Go to pull request'
        url: ${{ steps.terraform_pr.output.remoteUrl }}
        icon: github
      - title: 'To view more check documentation'
        icon: docs
        url: ${{ steps.template.tag }}